extends Node

enum RESOURCES_TRACKED{
	NONE, WOOD , FOOD , COINS ,HOMES ,STONE, VENISON, LEATHER
}

enum BUILDINGS{
	NONE = 0, HOUSE = 1, STORAGE = 2, FARM = 3, HARVEST = 4, ROAD = 5
}
enum WORKPLACE {
	NONE = 0, HUNT, CLOTH
}
enum JOB{
	NONE = 0, LABORER= 1, BUILDER = 2, FARMER = 3,HUNTER = 4
}
enum VILLAGER_STATE{
	WORKING, RESTING, SLEEPING
}

var build_queue = []
var tribute_payment : float

var value_dict : Dictionary = {
	RESOURCES_TRACKED.WOOD : 1,
	RESOURCES_TRACKED.FOOD : 2,
	RESOURCES_TRACKED.STONE : 2,
	RESOURCES_TRACKED.VENISON : 2,
	RESOURCES_TRACKED.LEATHER : 3,
}
var inventory_dict : Dictionary = {
	RESOURCES_TRACKED.NONE : 0,
	RESOURCES_TRACKED.WOOD : 10,
	RESOURCES_TRACKED.FOOD : 0,
	RESOURCES_TRACKED.COINS : 0,
	RESOURCES_TRACKED.HOMES : 0,
	RESOURCES_TRACKED.STONE : 0,
	RESOURCES_TRACKED.VENISON : 0,
	RESOURCES_TRACKED.LEATHER : 0,
}
var naming_dict : Dictionary = {
	RESOURCES_TRACKED.WOOD : "WOOD",
	RESOURCES_TRACKED.FOOD : "FOOD",
	RESOURCES_TRACKED.COINS : "COINS",
	RESOURCES_TRACKED.HOMES : "HOMES",
	RESOURCES_TRACKED.STONE : "STONE",
	RESOURCES_TRACKED.VENISON : "VENISON",
	RESOURCES_TRACKED.LEATHER : "LEATHER",
	
}
var stringResource_dict : Dictionary = {
	"WOOD" : RESOURCES_TRACKED.WOOD,
	"STONE" : RESOURCES_TRACKED.STONE,
	"FOOD" : RESOURCES_TRACKED.FOOD,
}


func set_villagers_state(state : VILLAGER_STATE) -> void:
	for villager in get_tree().get_nodes_in_group("VILLAGER"):
		villager.state = state
